name: Python coverage

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  python-test-coverage:
    name: Python Coverage
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: ['integration-tests', 'unit-tests', 'gui-tests']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: "pip"
        cache-dependency-path: |
          pyproject.toml

    - name: Install with dependencies
      run: |
        pip install ".[dev]"

    - name: Test GUI
      if: matrix.test-type == 'gui-tests'
      run: |
        pytest tests/gui --cov=ert --cov-report=xml:cov.xml -v

    - name: Test Integration
      if: matrix.test-type == 'integration-tests'
      run: |
        pytest tests/integration -n logical --cov=ert --cov-report=xml:cov.xml

    - name: Test units
      if: matrix.test-type == 'unit-tests'
      run: |
        pytest tests/unit -n logical --cov=ert --cov-report=xml:cov.xml --dist loadgroup

    - name: Upload python coverage to Codecov
      uses: codecov/codecov-action@v4
      id: codecov1
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: cov.xml
    - name: codecov retry sleep
      if: steps.codecov1.outcome == 'failure'
      run: |
        sleep 30
    - name: Codecov retry
      uses: codecov/codecov-action@v4
      if: steps.codecov1.outcome == 'failure'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cov.xml
        fail_ci_if_error: ${{ github.ref == 'refs/heads/main' }}
